# Задание №1

In [1]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).transpose()

In [6]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
mean_a = np.mean(a, axis = 0)

In [10]:
mean_a

array([2. , 8.4])

# Задание №2

In [23]:
a_centered = a - mean_a

In [24]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание №3

In [33]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]

In [34]:
a_centered_sp

8.0

In [40]:
a_centered_sp / (np.shape(a)[0] - 1)

2.0

# Задание №4

In [41]:
cov_matrix = np.cov(m = a.transpose())
cov_matrix

array([[1. , 2. ],
       [2. , 4.3]])

In [42]:
cov_matrix[0, 1] == a_centered_sp / (np.shape(a)[0] - 1)

True