# **Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [4]:
a = np.linspace(12, 23, 12).astype('int')
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [5]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [8]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [9]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [11]:
a.reshape(2, -1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [15]:
a.reshape(-1, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [16]:
a.reshape(-1, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [20]:
if a.reshape(-1, 1).ndim > 1:
    print('нельзя')
else:
    print('можно')

нельзя


5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [64]:
a = np.random.randn(3, 4)
a

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

In [28]:
b = a.flatten()
b

array([ 0.89024482, -2.43941636, -0.68941369, -1.135269  , -1.44874555,
        0.18026391,  1.79497272, -0.55466834,  0.52858336, -0.13111313,
        0.98437596,  0.6047598 ])

In [25]:
a.size

12

In [29]:
b.size

12

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [37]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [38]:
b = np.arange(20, 0, -2).reshape(1, -1)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [39]:
a.ndim

1

In [40]:
b.ndim

2

разница в количестве измерений массивов: в первом случае массив одномерный, а во втором - двухмерный

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [45]:
a = np.zeros([2, 2])
a

array([[0., 0.],
       [0., 0.]])

In [46]:
b = np.ones([3, 2])
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [50]:
c = np.concatenate((a, b), axis=0)
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [51]:
c.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [53]:
a = np.arange(0, 12, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [58]:
B = A @ At
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [59]:
B.size

16

In [61]:
np.linalg.det(B)

0.0

так как детерминант матрицы равен нулю, вычисление обратной матрицы невозможно

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42

In [62]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [74]:
c = np.random.default_rng().integers(0, 16, 16)
c

array([ 5, 10,  5,  5,  8,  5,  3,  3,  7, 12,  7,  2,  8, 13,  3, 15],
      dtype=int64)

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [75]:
C = c.reshape(4, 4)
C

array([[ 5, 10,  5,  5],
       [ 8,  5,  3,  3],
       [ 7, 12,  7,  2],
       [ 8, 13,  3, 15]], dtype=int64)

In [76]:
D = B + C * 10
D

array([[ 55, 114,  73,  82],
       [ 94, 100, 116, 152],
       [ 93, 206, 219, 232],
       [112, 252, 242, 452]], dtype=int64)

In [77]:
np.linalg.det(D)

-96127599.99999999

In [78]:
np.linalg.matrix_rank(D)

4

In [79]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00567829,  0.01994599, -0.009028  , -0.00310379],
       [ 0.01932806, -0.01059862, -0.00206226,  0.00111622],
       [-0.01775806,  0.00109812,  0.0156001 , -0.00515482],
       [-0.00267519,  0.00037866, -0.00496548,  0.00511903]])